# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.6.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.6.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mailund/Projects/ancpoly

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mailund/Projects/ancpoly

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.6.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.6.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mailund/Projects/ancpoly/CMakeFiles /Users/mailund/Projects/ancpoly/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mailund/Projects/ancpoly/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bin/sample_freqs

# Build rule for target.
bin/sample_freqs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/sample_freqs
.PHONY : bin/sample_freqs

# fast build rule for target.
bin/sample_freqs/fast:
	$(MAKE) -f CMakeFiles/bin/sample_freqs.dir/build.make CMakeFiles/bin/sample_freqs.dir/build
.PHONY : bin/sample_freqs/fast

src/io.o: src/io.c.o

.PHONY : src/io.o

# target to build an object file
src/io.c.o:
	$(MAKE) -f CMakeFiles/bin/sample_freqs.dir/build.make CMakeFiles/bin/sample_freqs.dir/src/io.c.o
.PHONY : src/io.c.o

src/io.i: src/io.c.i

.PHONY : src/io.i

# target to preprocess a source file
src/io.c.i:
	$(MAKE) -f CMakeFiles/bin/sample_freqs.dir/build.make CMakeFiles/bin/sample_freqs.dir/src/io.c.i
.PHONY : src/io.c.i

src/io.s: src/io.c.s

.PHONY : src/io.s

# target to generate assembly for a file
src/io.c.s:
	$(MAKE) -f CMakeFiles/bin/sample_freqs.dir/build.make CMakeFiles/bin/sample_freqs.dir/src/io.c.s
.PHONY : src/io.c.s

src/sample_freqs.o: src/sample_freqs.c.o

.PHONY : src/sample_freqs.o

# target to build an object file
src/sample_freqs.c.o:
	$(MAKE) -f CMakeFiles/bin/sample_freqs.dir/build.make CMakeFiles/bin/sample_freqs.dir/src/sample_freqs.c.o
.PHONY : src/sample_freqs.c.o

src/sample_freqs.i: src/sample_freqs.c.i

.PHONY : src/sample_freqs.i

# target to preprocess a source file
src/sample_freqs.c.i:
	$(MAKE) -f CMakeFiles/bin/sample_freqs.dir/build.make CMakeFiles/bin/sample_freqs.dir/src/sample_freqs.c.i
.PHONY : src/sample_freqs.c.i

src/sample_freqs.s: src/sample_freqs.c.s

.PHONY : src/sample_freqs.s

# target to generate assembly for a file
src/sample_freqs.c.s:
	$(MAKE) -f CMakeFiles/bin/sample_freqs.dir/build.make CMakeFiles/bin/sample_freqs.dir/src/sample_freqs.c.s
.PHONY : src/sample_freqs.c.s

src/sampling.o: src/sampling.c.o

.PHONY : src/sampling.o

# target to build an object file
src/sampling.c.o:
	$(MAKE) -f CMakeFiles/bin/sample_freqs.dir/build.make CMakeFiles/bin/sample_freqs.dir/src/sampling.c.o
.PHONY : src/sampling.c.o

src/sampling.i: src/sampling.c.i

.PHONY : src/sampling.i

# target to preprocess a source file
src/sampling.c.i:
	$(MAKE) -f CMakeFiles/bin/sample_freqs.dir/build.make CMakeFiles/bin/sample_freqs.dir/src/sampling.c.i
.PHONY : src/sampling.c.i

src/sampling.s: src/sampling.c.s

.PHONY : src/sampling.s

# target to generate assembly for a file
src/sampling.c.s:
	$(MAKE) -f CMakeFiles/bin/sample_freqs.dir/build.make CMakeFiles/bin/sample_freqs.dir/src/sampling.c.s
.PHONY : src/sampling.c.s

src/trees.o: src/trees.c.o

.PHONY : src/trees.o

# target to build an object file
src/trees.c.o:
	$(MAKE) -f CMakeFiles/bin/sample_freqs.dir/build.make CMakeFiles/bin/sample_freqs.dir/src/trees.c.o
.PHONY : src/trees.c.o

src/trees.i: src/trees.c.i

.PHONY : src/trees.i

# target to preprocess a source file
src/trees.c.i:
	$(MAKE) -f CMakeFiles/bin/sample_freqs.dir/build.make CMakeFiles/bin/sample_freqs.dir/src/trees.c.i
.PHONY : src/trees.c.i

src/trees.s: src/trees.c.s

.PHONY : src/trees.s

# target to generate assembly for a file
src/trees.c.s:
	$(MAKE) -f CMakeFiles/bin/sample_freqs.dir/build.make CMakeFiles/bin/sample_freqs.dir/src/trees.c.s
.PHONY : src/trees.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bin/sample_freqs"
	@echo "... src/io.o"
	@echo "... src/io.i"
	@echo "... src/io.s"
	@echo "... src/sample_freqs.o"
	@echo "... src/sample_freqs.i"
	@echo "... src/sample_freqs.s"
	@echo "... src/sampling.o"
	@echo "... src/sampling.i"
	@echo "... src/sampling.s"
	@echo "... src/trees.o"
	@echo "... src/trees.i"
	@echo "... src/trees.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

