---
title: "Wright-Fisher with Jukes-Cantor"
output: html_notebook
---

```{r setup}
library(bindr)
```

```{r}
simulate_next_generation_size <- function(N) max(1, round(rnorm(1, N, 2)))
simulate_next_generation <- function(N, x, mu) {
  new_N <- simulate_next_generation_size(N)
  new_z <- rbinom(1, new_N, x * (1 - mu) + (1 - x) * mu)
  new_x <- new_z / new_N
  c(new_N, new_z, new_x)
}
simulate_n_generations <- function(n, mu, start_N, start_z) {
  generations <- matrix(rep(NA, 3*n), nrow = n, ncol = 3)
  
  N <- start_N
  z <- start_z
  x <- start_z / start_N
  
  for (g in 1:n) {
    generations[g,] <- simulate_next_generation(N, x, mu)
    N <- generations[g,1]
    z <- generations[g,2]
    x <- generations[g,3]
  }
  
  colnames(generations) <- c("N", "z", "x")
  generations
}
```

```{r}
mu <- 0.1
N <- 10000
z <- 50

generations1 <- simulate_n_generations(100, mu, N, z)
generations2 <- simulate_n_generations(100, mu, N, z)
generations3 <- simulate_n_generations(100, mu, N/10, z)
generations4 <- simulate_n_generations(100, mu, N/10, z)
generations5 <- simulate_n_generations(100, mu, N*10, z)
generations6 <- simulate_n_generations(100, mu, N*10, z)
#plot(generations1[,"N"], type = "l", xlab = "Generation", ylab = "Generation Size")
#lines(generations2[,"N"], col = "blue")

#plot(generations1[,"z"], type = "l", xlab = "Generation", ylab = "Allele counts")
#lines(generations2[,"z"], col = "blue")

plot(generations1[,"x"], type = "l", xlab = "Generation", ylab = "Allele frequency", ylim = c(0, 1))
lines(generations2[,"x"], col = "black")
lines(generations3[,"x"], col = "red")
lines(generations4[,"x"], col = "red")
lines(generations5[,"x"], col = "blue")
lines(generations6[,"x"], col = "blue")
abline(h = 0.5, lty="dashed")
```
